<a href="https://colab.research.google.com/github/abhiii04-25/NLP-for-Machine-Learning/blob/main/Bag_of_words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from numpy import vectorize
from sklearn.feature_extraction.text import CountVectorizer

document=[
    "I Love pizza",
    "Pizza is best",
    "I love pasta",
    "Pasta is great"
]

vectorize=CountVectorizer(ngram_range=(2,2))
x=vectorize.fit_transform(document)

print("Vectorized:",vectorize.get_feature_names_out())

print("\nBow Martix:",x.toarray())


Vectorized: ['is best' 'is great' 'love pasta' 'love pizza' 'pasta is' 'pizza is']

Bow Martix: [[0 0 0 1 0 0]
 [1 0 0 0 0 1]
 [0 0 1 0 0 0]
 [0 1 0 0 1 0]]
